mysql -e "CREATE DATABASE SQL_DATABASE";
mysql -e "CREATE USER SQL_USER IDENTIFIED BY SQL_PASSWORD";
mysql -e "GRANT ALL PRIVILEGES ON SQL_DATABASE.* TO SQL_USER IDENTIFIED BY SQL_PASSWORD";
mysql -e "FLUSH PRIVILEGES";
#exit