CREATE DATABASE $(SQL_DATABASE);
CREATE USER $(SQL_USER) IDENTIFIED BY $(SQL_PASSWORD);
GRANT ALL PRIVILEGES ON $(SQL_DATABASE) TO $(SQL_USER) IDENTIFIED BY $(SQL_PASSWORD)
ALTER USER root IDENTIFIED BY $(SQL_ROOT_PASSWORD);
FLUSH PRIVILEGES;
exit