services:

  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure
    image: wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always
    image: nginx
    container_name: nginx
    networks:
      - inception
    env_file: .env

volumes:
  wordpress:
      driver_opts:
        type: none
        o: bind
        device: $VOLUME_DIR/wordpress
  mariadb:
      driver_opts:
        type: none
        o: bind
        device: $VOLUME_DIR/mariadb

networks:
  inception:
    driver: bridge