services:

  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure
    image: wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    image: nginx
    container_name: nginx
    networks:
      - inception
    env_file: .env

  redis:
    image: redis
    build: requirements/bonus/redis
    networks:
      - inception
    container_name: redis
    restart: on-failure

  ftp:
    image: ftp
    build: requirements/bonus/ftp/
    networks:
      - inception
    ports:
      - "21:21"
      - "7000-7010:7000-7010"
    volumes:
      - wordpress:/var/www/html
    container_name: ftp
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

  adminer:
    image: adminer
    build: requirements/bonus/adminer/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    container_name: adminer
    depends_on:
      - wordpress

  staticpage:
    image: staticpage
    build: requirements/bonus/staticpage/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    container_name: staticpage
    depends_on:
      - wordpress

  portainer:
    image: portainer
    build: requirements/bonus/portainer
    networks:
      - inception
    ports:
      - "12000:9000"
      - "12001:9443"
    container_name: portainer
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  wordpress:
      driver_opts:
        type: none
        o: bind
        device: $VOLUME_DIR/wordpress
  mariadb:
      driver_opts:
        type: none
        o: bind
        device: $VOLUME_DIR/mariadb

networks:
  inception:
    driver: bridge