services:

  mariadb:
    build: requirements/mariadb
    volumes:
      - /home/mariadb:/var/lib/mysql
    #stop_grace_period: 1s
    #restart: unless-stopped
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    build: requirements/wordpress
    volumes:
      - /home/wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    #restart: on-failure
    image: wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    image: nginx
    container_name: nginx
    networks:
      - inception
    env_file: .env

volumes:
  wordpress:
    driver: local
  mariadb:
    driver: local

networks:
  inception:
    driver: bridge